### ISSUE TITLE
[Onboarding Tracker] HighThroughputElasticNetworks

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/APIBacklog#133]
**API information**

- **Name**: HighThroughputElasticNetworks
- **Mail List**: [hten@lists.camaraproject.org](mailto:hten@lists.camaraproject.org)
- **Repository**: https://github.com/camaraproject/HighThroughputElasticNetworks
- **API owner**: @wangruobei 
- **Template**: https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIproposal_high-throughput-elastic-networks_ChinaMobile.md
- **Original Issue**: #89 

**Action List**

- [ ] Create repository
- [ ] Update of APIBacklog.md with new status 
- [ ] Get nominations of initial code owner(s) (one mandatory) **(API owner)** 
- [ ] Update CODEOWNERS file with PR
- [ ] Optional: get nominations of initial Maintainers **(API owner)** 
- [ ] Update Maintainers.md file with PR
- [ ] Create wiki page
- [ ] Create mailing list
- [ ] Create README with links to wiki page and mailing list
- [ ] Update README with API information **(API owner)** 
- [ ] Update of CAMARA presentation and website 

CC: @camaraproject/admins @camaraproject/api-backlog_maintainers @camaraproject/marketing_maintainers

**Comment by hdamker** [comment]
@camaraproject/api-backlog_maintainers The repository was created in November 2024, but no life-sign at all since then, even not the initial administrative issues are addressed. Should we consider to archive the repository until there is again some interest to drive this API?

**Comment by hdamker** [comment]
@jgarciahospital The repository is still lacking an initial code owner, what is the working group's proposal to proceed?

**Comment by wangruobei** [comment]
> [@jgarciahospital](https://github.com/jgarciahospital) The repository is still lacking an initial code owner, what is the working group's proposal to proceed?

Thank you for reminding. I've submitted a PR in the repository about updating code owner.

**Comment by wangruobei** [comment]
@hdamker Thank you for reminding. I've submitted a PR in the repository about updating code owner.

**Comment by hdamker** [comment]
Created PR to update README with mailing list and wiki page links. Need to be approved and merged by @wangruobei.

**Comment by hdamker** [comment]
Onboarding almost done, but scope description in README still not updated. No relevant activity in the repository since its creation.

**Comment by albertoramosmonagas** [comment]
Hi @camaraproject/high-throughput-elastic-networks_codeowners & @wangruobei, any relevant updates on the issue?

**Comment by wangruobei** [comment]
> Hi [@wangruobei](https://github.com/wangruobei),  你好 ，
> 
> As part of the post-fall 25 meta-release clean-up review ([camaraproject/Governance#199](https://github.com/camaraproject/Governance/issues/199)), this tracker has been identified as inactive since 1 August 2025. The initial onboarding steps are still pending, with no recent updates on the checklist or commits recorded.作为 2025 年秋季元版本清理审查 ( [camaraproject/Governance#199](https://github.com/camaraproject/Governance/issues/199) ) 的一部分，此跟踪器自 2025 年 8 月 1 日起被认定为不活跃。初始入职步骤仍在进行中，清单或提交记录中没有最近的更新。
> 
> **Response window**: until 24 November 2025**回复期限 **：至 2025 年 11 月 24 日
> 
> **Next steps**:**后续步骤 **：
> 
> * If progress is shared or the remaining onboarding actions are completed within this window, the tracker will remain active.如果在此时间内分享了进度或完成了剩余的入职流程，跟踪器将保持活动状态。
> * If no update is received by 24 November, the API Backlog Working Group will propose to close and archive this onboarding tracker in line with the unified Clean-up Process ([Governance § “Lifecycle Clean-up Process”](https://github.com/camaraproject/Governance/pull/201)).如果到 11 月 24 日仍未收到更新，API 积压工作工作组将提议按照统一的清理流程关闭并归档此入门跟踪器。
> * Ownership can be transferred to another CAMARA member before archival if there is continued interest.如果仍有持续的兴趣，所有权可以在存档前转让给另一位 CAMARA 成员。
> 
> Please confirm whether the current codeowners plan to continue onboarding.请确认现有代码所有者是否计划继续进行新成员加入。

We will continue to update the relevant content, so please do not clean up this issue and related information. Thank you for your attention and support!

**Comment by wangruobei** [comment]
> Hi [@wangruobei](https://github.com/wangruobei),  你好 ，
> 
> Any relevant updates on the remaining items?关于剩余项目，有任何相关更新吗？
> 
> * [ ]  Update README with API information (API owner)更新 README 文件，添加 API 信息（API 所有者）[ ]  Optional: get nominations of initial Maintainers (API owner)（可选）获取初始维护者（API 所有者）的提名[ ]  Update Maintainers.md file with PR更新 Maintainers.md 文件，添加 PR
> 
> This is the last step to close the onboarding tracker. I see you have an associated [issue](https://github.com/camaraproject/HighThroughputElasticNetworks/issues/3) for that, but a PR was already merged with the readme update.这是关闭新用户引导跟踪器的最后一步。我看到您为此提交了一个 [issue](https://github.com/camaraproject/HighThroughputElasticNetworks/issues/3) ，但相关的 PR 已经与 README 更新合并了。

@albertoramosmonagas We have completed the first task (updating the README.md file) and the third task (updating the Maintainers.md file). We will continue to supplement API-related information in its repository and proceed with the API release process as planned. Thank you for your support!
