### ISSUE TITLE
[Onboarding Tracker] CapabilityAndRuntimeRestrictions

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/APIBacklog#134]
**API information**

- **Name**: CapabilityAndRuntimeRestrictions
- **Mail List**: [sp-crr@lists.camaraproject.org](mailto:sp-crr@lists.camaraproject.org)
- **Repository**: https://github.com/camaraproject/CapabilitiesAndRuntimeRestrictions
- **Wiki Page**: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/52658409/CapabilitiesAndRuntimeRestrictions
- **API owner**: @gmuratk 
- **API proposal**: https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIproposal_CapabilitiesandRuntimeRestrictions_T-MobileUS.md
- **Original Issue**: #22 

**Action List**

- [x] Create repository
- [x] Update of APIBacklog.md with new status 
- [x] Get nominations of initial code owner(s) (one mandatory) **(API owner)** 
- [x] Update CODEOWNERS file with PR
- [x] Optional: get nominations of initial Maintainers **(API owner)** 
- [x] Update Maintainers.md file with PR
- [x] Create wiki page
- [x] Create mailing list
- [x] Create README with links to wiki page and mailing list
- [x] Update README with API information **(API owner)** 
- [x] Update of CAMARA presentation and website 

CC: @camaraproject/admins @camaraproject/api-backlog_maintainers @camaraproject/marketing_maintainers

**Comment by gmuratk** [comment]
Following can be updated with https://github.com/camaraproject/CapabilitiesAndRuntimeRestrictions/pull/4
> * [x]  Get nominations of initial code owner(s) (one mandatory) **(API owner)**
> * [x]  Update CODEOWNERS file with PR
> * [x]  Optional: get nominations of initial Maintainers **(API owner)**
> * [x]  Update Maintainers.md file with PR

**Comment by hdamker** [comment]
> * **Template**: _Pending_

@jgarciahospital: what is meant by "Template"?

**Comment by jgarciahospital** [comment]
API proposal template, which was not merged yet. Solved now.

**Comment by gmuratk** [comment]
Following items have been completed:

- [ ] Create README with links to wiki page and mailing list
- [ ] Update README with API information (API owner)
- [ ] Update of CAMARA presentation and website

link to updated website: https://camaraproject.org/capabilities-and-runtime-restrictions/ 
link to updated presentation: https://github.com/camaraproject/Marketing/blob/main/documentation/MarketingMaterial/CAMARA%20Presentation.pdf


Please note that the mailing list created differs from what's listed in the issue.

- mailing list email: sp-crr@lists.camaraproject.org
- mailing list subscription: https://lists.camaraproject.org/g/sp-crr

We plan to start the meetings on March 18, 2025

**Comment by hdamker** [comment]
@gmuratk I've updated the issue description with the correct mailing list and opened a short PR within the repository with some latest alignments of the README.

@jgarciahospital looks like all is done here.

**Comment by jgarciahospital** [comment]
Issue closed as resolved
