### ISSUE TITLE
[Onboarding Tracker] ModelAsAService

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/APIBacklog#162]
**API information**

- **Name**: ModelAsAService
- **Mail List**: sp-maas@lists.camaraproject.org
- **Repository**: https://github.com/camaraproject/ModelAsAService
- **Wiki Page**: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/52658427/ModelAsAService
- **API owner**: @lihaojie-CMCC
- **API proposal**: https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIFamily_Proposal_MaaS_ChinaMobile.md
https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/API_Proposal_KnowledgeBase_Manage_ChinaMobile.md
https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/API_Proposal_Q%26A_Assistant_Manage_ChinaMobile.md
https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/API_Proposal_Q%26A_Assistant_Service_ChinaMobile.md
- **Original Issue**: #83 

**Action List**

- [x] Create repository
- [x] Update of APIBacklog.md with new status 
- [x] Get nominations of initial code owner(s) (one mandatory) **(API owner)** 
- [x] Update CODEOWNERS file with PR
- [ ] Optional: get nominations of initial Maintainers **(API owner)** 
- [ ] Update Maintainers.md file with PR
- [x] Create wiki page
- [x] Create mailing list
- [x] Create README with links to wiki page and mailing list
- [x] Update README with API information **(API owner)** 
- [x] Update of CAMARA presentation and website 

CC: @camaraproject/admins @camaraproject/api-backlog_maintainers @camaraproject/marketing_maintainers

**Comment by hdamker** [comment]
I've invited the API owner @lihaojie-CMCC to join the @camaraproject/model-as-a-service_codeowners GitHub team as potential initial codeowner. And further updates on this onboarding?

**Comment by hdamker** [comment]
I created a PR https://github.com/camaraproject/ModelAsAService/pull/4 to set @lihaojie-CMCC as code owner. But there is unfortunately no life-sign in the repository since its creation in January. Are there any news when the work will start?

**Comment by hdamker** [comment]
Onboarding is completed, except
* Update of Maintainers.md is optional
* There is not yet an API description hence also no update of the website

**Comment by albertoramosmonagas** [comment]
Hi @jgarciahospital, following Herbert's message, the last pending task was completed: Update of CAMARA's presentation and website. Result at: https://camaraproject.org/model-as-a-service/. We can close the onboarding tracker.
